const { ROOM_IMAGES } = require("./site-images");

const DEFAULT_ROOMS = [
  {
    id: "standard-night",
    slug: "standard-night-stay",
    name: "Standard Night Stay",
    description: "Ideal for solo or couple travelers.",
    room_type: "Luxury Stay",
    price_per_night: 750,
    max_guests: 2,
    total_units: 8,
    amenities: JSON.stringify(["Fully Furnished Unit", "Secure Parking", "Peaceful Environment"]),
    image_url: ROOM_IMAGES["standard-night"],
    sort_order: 1,
  },
  {
    id: "shared-unit",
    slug: "shared-unit-stay",
    name: "Shared Unit Stay",
    description: "Great for friends or work teams.",
    room_type: "Shared Stay",
    price_per_night: 1400,
    max_guests: 4,
    total_units: 4,
    amenities: JSON.stringify(["2 Beds Per Unit", "Communal Kitchen Access", "Weekly Cleaning Service"]),
    image_url: ROOM_IMAGES["shared-unit"],
    sort_order: 2,
  },
  {
    id: "weekly-stay",
    slug: "weekly-stay-package",
    name: "Weekly Stay Package",
    description: "Hassle-free extended stays.",
    room_type: "Weekly Package",
    price_per_night: 0,
    max_guests: 2,
    total_units: 6,
    amenities: JSON.stringify(["Discounted Weekly Rates", "Priority Booking", "Laundry Service Available"]),
    image_url: ROOM_IMAGES["weekly-stay"],
    sort_order: 3,
  },
  {
    id: "monthly-rental",
    slug: "monthly-rental-package",
    name: "Monthly Rental Package",
    description: "Exclusive deal for bulk stays.",
    room_type: "Monthly Package",
    price_per_night: 8000,
    max_guests: 2,
    total_units: 2,
    amenities: JSON.stringify(["Private & Secure Units", "Access to All Facilities", "Long-term Convenience"]),
    image_url: ROOM_IMAGES["monthly-rental"],
    sort_order: 4,
  },
  {
    id: "safari-3day",
    slug: "3-day-safari-adventure",
    name: "3-Day Safari Adventure",
    description: "Curated safari experience package.",
    room_type: "Tour",
    price_per_night: 199,
    max_guests: 4,
    total_units: 5,
    amenities: JSON.stringify(["Guided Safari", "Accommodation Included", "Meals Available"]),
    image_url: ROOM_IMAGES["safari-3day"],
    sort_order: 5,
  },
  {
    id: "safari-7day",
    slug: "7-day-ultimate-experience",
    name: "7-Day Ultimate Experience",
    description: "Full week luxury tour package.",
    room_type: "Tour",
    price_per_night: 189,
    max_guests: 4,
    total_units: 5,
    amenities: JSON.stringify(["Premium Itinerary", "VIP Treatment", "Transport Included"]),
    image_url: ROOM_IMAGES["safari-7day"],
    sort_order: 6,
  },
  {
    id: "private-event",
    slug: "private-event-celebration",
    name: "Private Event / Celebration",
    description: "Host birthdays, corporate events, and celebrations.",
    room_type: "Event",
    price_per_night: 0,
    max_guests: 50,
    total_units: 1,
    amenities: JSON.stringify(["Flexible Setup", "Event Support", "Custom Quote"]),
    image_url: ROOM_IMAGES["private-event"],
    sort_order: 7,
  },
];
const PACKAGE_TO_ROOM = {
  "Standard Night Stay": "standard-night",
  "Shared Unit Stay": "shared-unit",
  "Weekly Stay Package": "weekly-stay",
  "Monthly Rental Package": "monthly-rental",
  "3-Day Safari Adventure": "safari-3day",
  "7-Day Ultimate Experience": "safari-7day",
  "Private Event / Celebration": "private-event",
};

module.exports = { DEFAULT_ROOMS, PACKAGE_TO_ROOM };
